// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace NGLBCMS.Models
{
    public partial class ActivityType
    {
        private string _activityIdentifier;
        
        /// <summary>
        /// Optional. Unique Identifier that describes specific activity type
        /// (ACTIVITY_TYPE_NIGHTFALL, etc)
        /// </summary>
        public string ActivityIdentifier
        {
            get { return this._activityIdentifier; }
            set { this._activityIdentifier = value; }
        }
        
        private string _activityTypeID;
        
        /// <summary>
        /// Optional. Unique ID (number, hash) that represents this Activity
        /// Type
        /// </summary>
        public string ActivityTypeID
        {
            get { return this._activityTypeID; }
            set { this._activityTypeID = value; }
        }
        
        private string _description;
        
        /// <summary>
        /// Optional. Activity Type Description (Join a fireteam of three and
        /// face the most feared minions of the Darkness.,etc)
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private string _iconPath;
        
        /// <summary>
        /// Optional. Activity Type Absolute Image Path (Strike Icon, Raid
        /// Icon, etc)
        /// </summary>
        public string IconPath
        {
            get { return this._iconPath; }
            set { this._iconPath = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional. Name of Activity Type (Strike, Raid, Bounty, etc)
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the ActivityType class.
        /// </summary>
        public ActivityType()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken activityIdentifierValue = inputObject["ActivityIdentifier"];
                if (activityIdentifierValue != null && activityIdentifierValue.Type != JTokenType.Null)
                {
                    this.ActivityIdentifier = ((string)activityIdentifierValue);
                }
                JToken activityTypeIDValue = inputObject["ActivityTypeID"];
                if (activityTypeIDValue != null && activityTypeIDValue.Type != JTokenType.Null)
                {
                    this.ActivityTypeID = ((string)activityTypeIDValue);
                }
                JToken descriptionValue = inputObject["Description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken iconPathValue = inputObject["IconPath"];
                if (iconPathValue != null && iconPathValue.Type != JTokenType.Null)
                {
                    this.IconPath = ((string)iconPathValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
            }
        }
    }
}
