// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using NGLBCMS.Models;
using Newtonsoft.Json.Linq;

namespace NGLBCMS.Models
{
    public partial class DailyWeeklyFinderContentResult
    {
        private Activity _dailyCrucible;
        
        /// <summary>
        /// Optional. Daily PVP Crucible Activity Object
        /// </summary>
        public Activity DailyCrucible
        {
            get { return this._dailyCrucible; }
            set { this._dailyCrucible = value; }
        }
        
        private Activity _dailyMission;
        
        /// <summary>
        /// Optional. Daily Story Mission Activity Object
        /// </summary>
        public Activity DailyMission
        {
            get { return this._dailyMission; }
            set { this._dailyMission = value; }
        }
        
        private Activity _heroicStrike;
        
        /// <summary>
        /// Optional. Weekly Heroic Strikes Activity Object
        /// </summary>
        public Activity HeroicStrike
        {
            get { return this._heroicStrike; }
            set { this._heroicStrike = value; }
        }
        
        private Activity _weeklyCrucible;
        
        /// <summary>
        /// Optional. Weekly PVP Crucible Activity Object
        /// </summary>
        public Activity WeeklyCrucible
        {
            get { return this._weeklyCrucible; }
            set { this._weeklyCrucible = value; }
        }
        
        private Activity _weeklyNightfall;
        
        /// <summary>
        /// Optional. Weekly Nightfall Strike Activity Object
        /// </summary>
        public Activity WeeklyNightfall
        {
            get { return this._weeklyNightfall; }
            set { this._weeklyNightfall = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the DailyWeeklyFinderContentResult
        /// class.
        /// </summary>
        public DailyWeeklyFinderContentResult()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken dailyCrucibleValue = inputObject["DailyCrucible"];
                if (dailyCrucibleValue != null && dailyCrucibleValue.Type != JTokenType.Null)
                {
                    Activity activity = new Activity();
                    activity.DeserializeJson(dailyCrucibleValue);
                    this.DailyCrucible = activity;
                }
                JToken dailyMissionValue = inputObject["DailyMission"];
                if (dailyMissionValue != null && dailyMissionValue.Type != JTokenType.Null)
                {
                    Activity activity2 = new Activity();
                    activity2.DeserializeJson(dailyMissionValue);
                    this.DailyMission = activity2;
                }
                JToken heroicStrikeValue = inputObject["HeroicStrike"];
                if (heroicStrikeValue != null && heroicStrikeValue.Type != JTokenType.Null)
                {
                    Activity activity3 = new Activity();
                    activity3.DeserializeJson(heroicStrikeValue);
                    this.HeroicStrike = activity3;
                }
                JToken weeklyCrucibleValue = inputObject["WeeklyCrucible"];
                if (weeklyCrucibleValue != null && weeklyCrucibleValue.Type != JTokenType.Null)
                {
                    Activity activity4 = new Activity();
                    activity4.DeserializeJson(weeklyCrucibleValue);
                    this.WeeklyCrucible = activity4;
                }
                JToken weeklyNightfallValue = inputObject["WeeklyNightfall"];
                if (weeklyNightfallValue != null && weeklyNightfallValue.Type != JTokenType.Null)
                {
                    Activity activity5 = new Activity();
                    activity5.DeserializeJson(weeklyNightfallValue);
                    this.WeeklyNightfall = activity5;
                }
            }
        }
    }
}
