// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace NGLBCMS.Models
{
    public partial class Skull
    {
        private string _description;
        
        /// <summary>
        /// Optional. Description of Skull (ability recharge slower, etc)
        /// </summary>
        public string Description
        {
            get { return this._description; }
            set { this._description = value; }
        }
        
        private string _iconPath;
        
        /// <summary>
        /// Optional. Absolute Image Path to Skull Icon
        /// </summary>
        public string IconPath
        {
            get { return this._iconPath; }
            set { this._iconPath = value; }
        }
        
        private string _name;
        
        /// <summary>
        /// Optional. Name of Skull (trickle, etc)
        /// </summary>
        public string Name
        {
            get { return this._name; }
            set { this._name = value; }
        }
        
        private string _skullID;
        
        /// <summary>
        /// Optional. The Skull's Unique Identifier (number, hash)
        /// </summary>
        public string SkullID
        {
            get { return this._skullID; }
            set { this._skullID = value; }
        }
        
        private string _skullIdentifier;
        
        /// <summary>
        /// Optional. Unique String Key that reprsents Skull Identifier
        /// (SKULL_TRICKLE)
        /// </summary>
        public string SkullIdentifier
        {
            get { return this._skullIdentifier; }
            set { this._skullIdentifier = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Skull class.
        /// </summary>
        public Skull()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken descriptionValue = inputObject["Description"];
                if (descriptionValue != null && descriptionValue.Type != JTokenType.Null)
                {
                    this.Description = ((string)descriptionValue);
                }
                JToken iconPathValue = inputObject["IconPath"];
                if (iconPathValue != null && iconPathValue.Type != JTokenType.Null)
                {
                    this.IconPath = ((string)iconPathValue);
                }
                JToken nameValue = inputObject["Name"];
                if (nameValue != null && nameValue.Type != JTokenType.Null)
                {
                    this.Name = ((string)nameValue);
                }
                JToken skullIDValue = inputObject["SkullID"];
                if (skullIDValue != null && skullIDValue.Type != JTokenType.Null)
                {
                    this.SkullID = ((string)skullIDValue);
                }
                JToken skullIdentifierValue = inputObject["SkullIdentifier"];
                if (skullIdentifierValue != null && skullIdentifierValue.Type != JTokenType.Null)
                {
                    this.SkullIdentifier = ((string)skullIdentifierValue);
                }
            }
        }
    }
}
